kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: {{ .Namespace }}

resources:
  - ../infra

configMapGenerator:
  - name: {{ .ServiceName }}
    envs:
      - configs/{{ .EnvPrefix }}/.env
{{- if and (eq .EnvPrefix "prod") (eq .IncludeBeta "yes") }}
  - name: beta-{{ .ServiceName }}
    envs:
      - configs/beta/.env
{{- end }}

patches:
  - path: image/{{ .EnvPrefix }}/image-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: {{ .ServiceName }}

{{- if and (eq .EnvPrefix "prod") (eq .IncludeBeta "yes") }}
  - path: image/beta/image-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: beta-{{ .ServiceName }}
{{- end }}