apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .ServiceName }}
  labels:
    app: {{ .ServiceName }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  refreshInterval: "1m"
  target:
    name: {{ .ServiceName }}
  dataFrom:
    - extract:
        key: {{ .SecretsPath }}